[package]
name = "game-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
thiserror = "2.0.17"
tokio = { version = "1", features = ["time"] }
uuid = { version = "1.19.0", features = ["v4"] }
