[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
tokio = { workspace = true }
adapters = { path = "../adapters" }
application = { path = "../application" }
tracing.workspace = true
tracing-subscriber.workspace = true
